<eclipse>
<error date="1/1/2007" time="0.00000000000000">
 UNRECOGNISED KEYWORD COMPS    IN RUNSPEC DATA                           
</error>
<warning date="1/1/2007" time="0.00000000000000">
 SPURIOUS DATA BEFORE EQLDIMS  KEYWORD                                   
 7 /                                                                     
</warning>
<error date="1/1/2007" time="0.00000000000000">
 UNRECOGNISED KEYWORD ASPHALTE IN RUNSPEC DATA                           
</error>
<warning date="1/1/2007" time="0.00000000000000">
 SPURIOUS DATA BEFORE GRID     KEYWORD                                   
   WEIGHT  /                                                             
</warning>
<message date="1/1/2007" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/2007" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
      28528 BYTES                                                        
</message>
<message date="1/1/2007" time="0.00000000000000">
 UNSPECIFIED TOPS VALUES OBTAINED BY ADDING DZ                           
 TO TOPS VALUE FOR LAYER ABOVE                                           
</message>
<message date="1/1/2007" time="0.00000000000000">
 NEITHER OLDTRAN,OLDTRANR NOR NEWTRAN SPECIFIED                          
 BLOCK CENTRE TRANSMISSIBILITIES TO BE CALCULATED                        
 USING  OLDTRAN                                                          
</message>
<comment date="1/1/2007" time="0.00000000000000">
 NO NON-NEIGHBOUR CONNECTIONS FOUND                                      
</comment>
<message date="1/1/2007" time="0.00000000000000">
 NUMBER OF ACTIVE CELLS IS 12                                            
</message>
<message date="1/1/2007" time="0.00000000000000">
 ADDITIONAL     0.004 MEGABYTES REQUIRED FOR SIMULATION                  
</message>
<message date="1/1/2007" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SOLUTION SECTION IS                  
     249764 BYTES                                                        
</message>
<message date="1/1/2007" time="0.00000000000000">
    58535 CHARACTER VARIABLES USED                                       
</message>
<error date="1/1/2007" time="0.00000000000000">
 UNRECOGNISED KEYWORD STCOND   IN PROPERTY DATA                          
</error>
<warning date="1/1/2007" time="0.00000000000000">
 SPURIOUS DATA BEFORE RTEMP    KEYWORD                                   
   60     14.7 /                                                         
</warning>
<error date="1/1/2007" time="0.00000000000000">
 UNRECOGNISED KEYWORD EOS      IN PROPERTY DATA                          
</error>
<warning date="1/1/2007" time="0.00000000000000">
 SPURIOUS DATA BEFORE PRCORR   KEYWORD                                   
    PR  /                                                                
</warning>
<error date="1/1/2007" time="0.00000000000000">
 UNRECOGNISED KEYWORD PRCORR   IN PROPERTY DATA                          
</error>
<error date="1/1/2007" time="0.00000000000000">
 UNRECOGNISED KEYWORD CNAMES   IN PROPERTY DATA                          
</error>
<warning date="1/1/2007" time="0.00000000000000">
 SPURIOUS DATA BEFORE MW       KEYWORD                                   
             C1       C3       C6        C10      C15       C20          
</warning>
<error date="1/1/2007" time="0.00000000000000">
 UNRECOGNISED KEYWORD MW       IN PROPERTY DATA                          
</error>
<warning date="1/1/2007" time="0.00000000000000">
 SPURIOUS DATA BEFORE TCRIT    KEYWORD                                   
          16.04    44.10    86.18    149.29    206.00    282.00          
</warning>
<error date="1/1/2007" time="0.00000000000000">
 UNRECOGNISED KEYWORD TCRIT    IN PROPERTY DATA                          
</error>
<warning date="1/1/2007" time="0.00000000000000">
 SPURIOUS DATA BEFORE PCRIT    KEYWORD                                   
         343.00   665.70   913.40   1111.80   1270.00   1380.00          
</warning>
<error date="1/1/2007" time="0.00000000000000">
 UNRECOGNISED KEYWORD PCRIT    IN PROPERTY DATA                          
</error>
<warning date="1/1/2007" time="0.00000000000000">
 SPURIOUS DATA BEFORE ZCRIT    KEYWORD                                   
         667.80   616.30   436.90    304.00    200.00    162.00          
</warning>
<error date="1/1/2007" time="0.00000000000000">
 UNRECOGNISED KEYWORD ZCRIT    IN PROPERTY DATA                          
 Stop limit reached on error      outputs
</error>
<warning date="1/1/2007" time="0.00000000000000">
 SPURIOUS DATA BEFORE ACF      KEYWORD                                   
          0.290    0.277    0.264     0.257     0.245     0.235          
</warning>
<error date="1/1/2007" time="0.00000000000000">
 UNRECOGNISED KEYWORD ACF      IN PROPERTY DATA                          
</error>
<error date="1/1/2007" time="0.00000000000000">
 RUN STOPPED BECAUSE NUMBER OF   ERRORS                                  
 EXCEEDS MAXIMUM PERMITTED VALUE (    10).                               
 SEE MESSAGES KEYWORD                                                    
</error>
</eclipse>
