<eclipse>
<error date="1/1/2003" time="0.00000000000000">
 UNRECOGNISED KEYWORD CO2STORE IN RUNSPEC DATA                           
</error>
<error date="1/1/2003" time="0.00000000000000">
 UNRECOGNISED KEYWORD THERMAL  IN RUNSPEC DATA                           
</error>
<error date="1/1/2003" time="0.00000000000000">
 UNRECOGNISED KEYWORD COMPS    IN RUNSPEC DATA                           
</error>
<warning date="1/1/2003" time="0.00000000000000">
 SPURIOUS DATA BEFORE FULLIMP  KEYWORD                                   
 4                                                                       
 /                                                                       
</warning>
<error date="1/1/2003" time="0.00000000000000">
 THERE ARE NO PHASES PRESENT. SPECIFY KEYWORDS                           
 OIL/WATER/GAS IN THE RUNSPEC SECTION                                    
</error>
<error date="1/1/2003" time="0.00000000000000">
 NO PHASES SPECIFIED AS BEING PRESENT IN RESERVOIR                       
 THERE MUST BE AT LEAST ONE ( OF OIL, WATER AND GAS )                    
</error>
<message date="1/1/2003" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<error date="1/1/2003" time="0.00000000000000">
 LICENSE FAILURE: ERROR NUMBER IS -1                                     
</error>
</eclipse>
