<eclipse>
<error date="1/1/0" time="0.00000000000000">
 UNRECOGNISED KEYWORD CO2SOL   IN RUNSPEC DATA                           
</error>
<error date="1/1/0" time="0.00000000000000">
 UNRECOGNISED KEYWORD COMPS    IN RUNSPEC DATA                           
</error>
<warning date="1/1/0" time="0.00000000000000">
 SPURIOUS DATA BEFORE EOS      KEYWORD                                   
 1 /                                                                     
</warning>
<error date="1/1/0" time="0.00000000000000">
 UNRECOGNISED KEYWORD EOS      IN RUNSPEC DATA                           
</error>
<error date="1/1/0" time="0.00000000000000">
 UNRECOGNISED KEYWORD PR /     IN RUNSPEC DATA                           
</error>
<warning date="1/1/2007" time="0.00000000000000">
 THE NUMBER OF WELLS HAS BEEN DEFAULTED TO ZERO                          
 USING KEYWORD WELLDIMS IN THE RUNSPEC SECTION                           
 OR NO WELLS WERE FOUND IN THE SCHEDULE SECTION                          
</warning>
<message date="1/1/2007" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<error date="1/1/2007" time="0.00000000000000">
 LICENSE FAILURE: ERROR NUMBER IS -1                                     
</error>
</eclipse>
