<eclipse>
<error date="1/1/2003" time="0.00000000000000">
 UNRECOGNISED KEYWORD CO2STORE IN RUNSPEC DATA                           
</error>
<error date="1/1/2003" time="0.00000000000000">
 UNRECOGNISED KEYWORD THERMAL  IN RUNSPEC DATA                           
</error>
<error date="1/1/2003" time="0.00000000000000">
 UNRECOGNISED KEYWORD COMPS    IN RUNSPEC DATA                           
</error>
<warning date="1/1/2003" time="0.00000000000000">
 SPURIOUS DATA BEFORE FULLIMP  KEYWORD                                   
 4                                                                       
 /                                                                       
</warning>
<error date="1/1/2003" time="0.00000000000000">
 THERE ARE NO PHASES PRESENT. SPECIFY KEYWORDS                           
 OIL/WATER/GAS IN THE RUNSPEC SECTION                                    
</error>
<error date="1/1/2003" time="0.00000000000000">
 NO PHASES SPECIFIED AS BEING PRESENT IN RESERVOIR                       
 THERE MUST BE AT LEAST ONE ( OF OIL, WATER AND GAS )                    
</error>
<message date="1/1/2003" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/2003" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
     126140 BYTES                                                        
</message>
<warning date="1/1/2003" time="0.00000000000000">
    200 VALUES NOT DEFINED IN BOX (  1- 10,  1- 10,  1-  3)              
 OF KEYWORD TOPS                                                         
</warning>
<error date="1/1/2003" time="0.00000000000000">
 UNRECOGNISED KEYWORD DZV      IN GRID DATA                              
</error>
<warning date="1/1/2003" time="0.00000000000000">
 SPURIOUS DATA BEFORE EQUALS   KEYWORD                                   
 3*10 /                                                                  
</warning>
<error date="1/1/2003" time="0.00000000000000">
 INVALID GRID ARRAY NAME HEATCR                                          
 ON RECORD    1 FOLLOWING EQUALS   KEYWORD                               
</error>
<error date="1/1/2003" time="0.00000000000000">
 GRID ARRAY THCONR   NOT ALLOWED WITH CURRENT                            
 RUNSPEC OPTIONS. SEE KEYWORD TEMP                                       
</error>
<warning date="1/1/2003" time="0.00000000000000">
 FLUX FLAG SET IN RUNSPEC BUT FLUXNUM KEYWORD                            
 NOT USED -- SAVE SPACE BY SETTING NTFREG = 0                            
 IN RUNSPEC KEYWORD REGDIMS.                                             
</warning>
<message date="1/1/2003" time="0.00000000000000">
 UNSPECIFIED TOPS VALUES OBTAINED BY ADDING DZ                           
 TO TOPS VALUE FOR LAYER ABOVE                                           
</message>
<message date="1/1/2003" time="0.00000000000000">
 NEITHER OLDTRAN,OLDTRANR NOR NEWTRAN SPECIFIED                          
 BLOCK CENTRE TRANSMISSIBILITIES TO BE CALCULATED                        
 USING  OLDTRAN                                                          
</message>
<error date="1/1/2003" time="0.00000000000000">
 INSUFFICIENT DATA TO COMPUTE PORE VOLUMES                               
 PORE VOLUMES WILL BE SET TO ZERO                                        
</error>
<error date="1/1/2003" time="0.00000000000000">
 INSUFFICIENT DATA TO COMPUTE CELL CENTRE DEPTHS                         
 Stop limit reached on error      outputs
</error>
<error date="1/1/2003" time="0.00000000000000">
 INSUFFICIENT DATA TO COMPUTE X TRANSMISSIBILITIES                       
</error>
<error date="1/1/2003" time="0.00000000000000">
 RUN STOPPED BECAUSE NUMBER OF   ERRORS                                  
 EXCEEDS MAXIMUM PERMITTED VALUE (    10).                               
 SEE MESSAGES KEYWORD                                                    
</error>
</eclipse>
