<eclipse>
<message date="1/1/1970" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/1970" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
     947928 BYTES                                                        
</message>
<message date="1/1/1970" time="0.00000000000000">
 NEITHER OLDTRAN,OLDTRANR NOR NEWTRAN SPECIFIED                          
 TRANSMISSIBILITIES TO BE CALCULATED                                     
 USING  NEWTRAN                                                          
</message>
<message date="1/1/1970" time="0.00000000000000">
 530 NON-NEIGHBOUR CONNECTIONS PRESENT                                   
</message>
<message date="1/1/1970" time="0.00000000000000">
 NUMBER OF ACTIVE CELLS IS 2351                                          
</message>
<message date="1/1/1970" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SOLUTION SECTION IS                  
      10233 KBYTES                                                       
</message>
<message date="1/1/1970" time="0.00000000000000">
    58886 CHARACTER VARIABLES USED                                       
</message>
<warning date="1/1/1970" time="0.00000000000000">
 UNRECOGNISED MNEMONIC DYNREG           IN DATA                          
 FOR KEYWORD RPTSOL   IS IGNORED                                         
</warning>
<warning date="1/1/1970" time="0.00000000000000">
 THE BOTTOM HOLE PRESSURE LIMIT FOR WELL VW3                             
 HAS BEEN DEFAULTED. THE DEFAULT VALUE IS    6891.   BARSA               
</warning>
<warning date="1/1/1970" time="0.00000000000000">
 THE PREFERRED PHASE FOR WELL VW3      IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<message date="1/1/1970" time="0.00000000000000">
 DRSDT KEYWORD HAS NOT BEEN ENTERED, SO THE                              
 MAXIMUM GAS RE-SOLUTION RATE IS DEFAULTED TO INFINITY.                  
</message>
<message date="1/1/1970" time="0.00000000000000">
 RESTART FILE WRITTEN   REPORT     0                                     
</message>
<message date="2/1/1970" time="1.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="2/1/1970" time="1.00000000000000">
 RESTART FILE WRITTEN   REPORT     1                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="5/1/1970" time="4.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="14/1/1970" time="13.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="14/1/1970" time="13.00000000000000">
 ******************************************                              
 * WELL VW1      HAS CHANGED TO           *                              
 * CONTROL BY BOTTOM HOLE PRESSURE        *                              
 * FROM TIME     13.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="1/2/1970" time="31.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="1/2/1970" time="31.00000000000000">
 RESTART FILE WRITTEN   REPORT     2                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="3/3/1970" time="61.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="3/3/1970" time="61.00000000000000">
 RESTART FILE WRITTEN   REPORT     3                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="2/4/1970" time="91.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="2/4/1970" time="91.00000000000000">
 RESTART FILE WRITTEN   REPORT     4                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="2/5/1970" time="121.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="2/5/1970" time="121.00000000000000">
 RESTART FILE WRITTEN   REPORT     5                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="1/6/1970" time="151.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="1/6/1970" time="151.00000000000000">
 RESTART FILE WRITTEN   REPORT     6                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="1/7/1970" time="181.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="1/7/1970" time="181.00000000000000">
 RESTART FILE WRITTEN   REPORT     7                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="31/7/1970" time="211.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="31/7/1970" time="211.00000000000000">
 RESTART FILE WRITTEN   REPORT     8                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="30/8/1970" time="241.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="30/8/1970" time="241.00000000000000">
 RESTART FILE WRITTEN   REPORT     9                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="29/9/1970" time="271.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="29/9/1970" time="271.00000000000000">
 RESTART FILE WRITTEN   REPORT    10                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="29/10/1970" time="301.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="29/10/1970" time="301.00000000000000">
 RESTART FILE WRITTEN   REPORT    11                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="28/11/1970" time="331.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="28/11/1970" time="331.00000000000000">
 RESTART FILE WRITTEN   REPORT    12                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="28/12/1970" time="361.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="28/12/1970" time="361.00000000000000">
 RESTART FILE WRITTEN   REPORT    13                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="27/1/1971" time="391.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="27/1/1971" time="391.00000000000000">
 RESTART FILE WRITTEN   REPORT    14                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="26/2/1971" time="421.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="26/2/1971" time="421.00000000000000">
 RESTART FILE WRITTEN   REPORT    15                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="28/3/1971" time="451.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="28/3/1971" time="451.00000000000000">
 RESTART FILE WRITTEN   REPORT    16                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="27/4/1971" time="481.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="27/4/1971" time="481.00000000000000">
 RESTART FILE WRITTEN   REPORT    17                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="27/5/1971" time="511.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="27/5/1971" time="511.00000000000000">
 RESTART FILE WRITTEN   REPORT    18                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="26/6/1971" time="541.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="26/6/1971" time="541.00000000000000">
 RESTART FILE WRITTEN   REPORT    19                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="26/7/1971" time="571.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="26/7/1971" time="571.00000000000000">
 RESTART FILE WRITTEN   REPORT    20                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="25/8/1971" time="601.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="25/8/1971" time="601.00000000000000">
 RESTART FILE WRITTEN   REPORT    21                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="24/9/1971" time="631.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="24/9/1971" time="631.00000000000000">
 RESTART FILE WRITTEN   REPORT    22                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="24/10/1971" time="661.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="24/10/1971" time="661.00000000000000">
 RESTART FILE WRITTEN   REPORT    23                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="23/11/1971" time="691.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="23/11/1971" time="691.00000000000000">
 RESTART FILE WRITTEN   REPORT    24                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="23/12/1971" time="721.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="23/12/1971" time="721.00000000000000">
 RESTART FILE WRITTEN   REPORT    25                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="22/1/1972" time="751.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="22/1/1972" time="751.00000000000000">
 RESTART FILE WRITTEN   REPORT    26                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="21/2/1972" time="781.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="21/2/1972" time="781.00000000000000">
 RESTART FILE WRITTEN   REPORT    27                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="22/3/1972" time="811.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="22/3/1972" time="811.00000000000000">
 RESTART FILE WRITTEN   REPORT    28                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="21/4/1972" time="841.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="21/4/1972" time="841.00000000000000">
 RESTART FILE WRITTEN   REPORT    29                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="21/5/1972" time="871.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="21/5/1972" time="871.00000000000000">
 RESTART FILE WRITTEN   REPORT    30                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="20/6/1972" time="901.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="20/6/1972" time="901.00000000000000">
 RESTART FILE WRITTEN   REPORT    31                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="20/7/1972" time="931.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="20/7/1972" time="931.00000000000000">
 RESTART FILE WRITTEN   REPORT    32                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="19/8/1972" time="961.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="19/8/1972" time="961.00000000000000">
 RESTART FILE WRITTEN   REPORT    33                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="18/9/1972" time="991.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="18/9/1972" time="991.00000000000000">
 RESTART FILE WRITTEN   REPORT    34                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="18/10/1972" time="1021.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="18/10/1972" time="1021.00000000000000">
 RESTART FILE WRITTEN   REPORT    35                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="17/11/1972" time="1051.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="17/11/1972" time="1051.00000000000000">
 RESTART FILE WRITTEN   REPORT    36                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="17/12/1972" time="1081.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="17/12/1972" time="1081.00000000000000">
 RESTART FILE WRITTEN   REPORT    37                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="16/1/1973" time="1111.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="16/1/1973" time="1111.00000000000000">
 RESTART FILE WRITTEN   REPORT    38                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="15/2/1973" time="1141.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="15/2/1973" time="1141.00000000000000">
 RESTART FILE WRITTEN   REPORT    39                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="17/3/1973" time="1171.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="17/3/1973" time="1171.00000000000000">
 RESTART FILE WRITTEN   REPORT    40                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="16/4/1973" time="1201.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="16/4/1973" time="1201.00000000000000">
 RESTART FILE WRITTEN   REPORT    41                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="16/5/1973" time="1231.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="16/5/1973" time="1231.00000000000000">
 RESTART FILE WRITTEN   REPORT    42                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="15/6/1973" time="1261.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="15/6/1973" time="1261.00000000000000">
 RESTART FILE WRITTEN   REPORT    43                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="15/7/1973" time="1291.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="15/7/1973" time="1291.00000000000000">
 RESTART FILE WRITTEN   REPORT    44                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="14/8/1973" time="1321.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="14/8/1973" time="1321.00000000000000">
 RESTART FILE WRITTEN   REPORT    45                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="13/9/1973" time="1351.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="13/9/1973" time="1351.00000000000000">
 RESTART FILE WRITTEN   REPORT    46                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="13/10/1973" time="1381.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="13/10/1973" time="1381.00000000000000">
 RESTART FILE WRITTEN   REPORT    47                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="12/11/1973" time="1411.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="12/11/1973" time="1411.00000000000000">
 RESTART FILE WRITTEN   REPORT    48                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="12/12/1973" time="1441.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="12/12/1973" time="1441.00000000000000">
 RESTART FILE WRITTEN   REPORT    49                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="11/1/1974" time="1471.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="11/1/1974" time="1471.00000000000000">
 RESTART FILE WRITTEN   REPORT    50                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="10/2/1974" time="1501.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="10/2/1974" time="1501.00000000000000">
 RESTART FILE WRITTEN   REPORT    51                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="12/3/1974" time="1531.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="12/3/1974" time="1531.00000000000000">
 RESTART FILE WRITTEN   REPORT    52                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="11/4/1974" time="1561.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="11/4/1974" time="1561.00000000000000">
 RESTART FILE WRITTEN   REPORT    53                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="11/5/1974" time="1591.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="11/5/1974" time="1591.00000000000000">
 RESTART FILE WRITTEN   REPORT    54                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="10/6/1974" time="1621.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="10/6/1974" time="1621.00000000000000">
 RESTART FILE WRITTEN   REPORT    55                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="10/7/1974" time="1651.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="10/7/1974" time="1651.00000000000000">
 RESTART FILE WRITTEN   REPORT    56                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="9/8/1974" time="1681.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="9/8/1974" time="1681.00000000000000">
 RESTART FILE WRITTEN   REPORT    57                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="8/9/1974" time="1711.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="8/9/1974" time="1711.00000000000000">
 RESTART FILE WRITTEN   REPORT    58                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="8/10/1974" time="1741.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="8/10/1974" time="1741.00000000000000">
 RESTART FILE WRITTEN   REPORT    59                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="7/11/1974" time="1771.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="7/11/1974" time="1771.00000000000000">
 RESTART FILE WRITTEN   REPORT    60                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="7/12/1974" time="1801.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="7/12/1974" time="1801.00000000000000">
 RESTART FILE WRITTEN   REPORT    61                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="6/1/1975" time="1831.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="6/1/1975" time="1831.00000000000000">
 RESTART FILE WRITTEN   REPORT    62                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="5/2/1975" time="1861.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="5/2/1975" time="1861.00000000000000">
 RESTART FILE WRITTEN   REPORT    63                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="7/3/1975" time="1891.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="7/3/1975" time="1891.00000000000000">
 RESTART FILE WRITTEN   REPORT    64                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="6/4/1975" time="1921.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="6/4/1975" time="1921.00000000000000">
 RESTART FILE WRITTEN   REPORT    65                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="6/5/1975" time="1951.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="6/5/1975" time="1951.00000000000000">
 RESTART FILE WRITTEN   REPORT    66                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="5/6/1975" time="1981.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="5/6/1975" time="1981.00000000000000">
 RESTART FILE WRITTEN   REPORT    67                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="5/7/1975" time="2011.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="5/7/1975" time="2011.00000000000000">
 RESTART FILE WRITTEN   REPORT    68                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="4/8/1975" time="2041.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="4/8/1975" time="2041.00000000000000">
 RESTART FILE WRITTEN   REPORT    69                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="3/9/1975" time="2071.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="3/9/1975" time="2071.00000000000000">
 RESTART FILE WRITTEN   REPORT    70                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="3/10/1975" time="2101.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="3/10/1975" time="2101.00000000000000">
 RESTART FILE WRITTEN   REPORT    71                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="2/11/1975" time="2131.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="2/11/1975" time="2131.00000000000000">
 RESTART FILE WRITTEN   REPORT    72                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="2/12/1975" time="2161.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="2/12/1975" time="2161.00000000000000">
 RESTART FILE WRITTEN   REPORT    73                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="1/1/1976" time="2191.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="1/1/1976" time="2191.00000000000000">
 RESTART FILE WRITTEN   REPORT    74                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="31/1/1976" time="2221.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="31/1/1976" time="2221.00000000000000">
 RESTART FILE WRITTEN   REPORT    75                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="1/3/1976" time="2251.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="1/3/1976" time="2251.00000000000000">
 RESTART FILE WRITTEN   REPORT    76                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="31/3/1976" time="2281.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="31/3/1976" time="2281.00000000000000">
 RESTART FILE WRITTEN   REPORT    77                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="30/4/1976" time="2311.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="30/4/1976" time="2311.00000000000000">
 RESTART FILE WRITTEN   REPORT    78                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="30/5/1976" time="2341.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="30/5/1976" time="2341.00000000000000">
 RESTART FILE WRITTEN   REPORT    79                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="29/6/1976" time="2371.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="29/6/1976" time="2371.00000000000000">
 RESTART FILE WRITTEN   REPORT    80                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="29/7/1976" time="2401.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="29/7/1976" time="2401.00000000000000">
 RESTART FILE WRITTEN   REPORT    81                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="28/8/1976" time="2431.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="28/8/1976" time="2431.00000000000000">
 RESTART FILE WRITTEN   REPORT    82                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="27/9/1976" time="2461.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="27/9/1976" time="2461.00000000000000">
 RESTART FILE WRITTEN   REPORT    83                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="27/10/1976" time="2491.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="27/10/1976" time="2491.00000000000000">
 RESTART FILE WRITTEN   REPORT    84                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="26/11/1976" time="2521.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="26/11/1976" time="2521.00000000000000">
 **********************************************************              
 * ACTION ACT      WILL BE ACTIVATED AT TIME       2521.00*              
 * BY REGION   1 FAMILY FIPYYY                            *              
 * SINCE ITS RPR__YYY HAS A VALUE OF    199.980591 WHICH  *              
 * IS &lt; THAN THE ACTION TRIGGERING VALUE OF    200.000000 *           
 **********************************************************              
</message>
<message date="26/11/1976" time="2521.00000000000000">
 RESTART FILE WRITTEN   REPORT    85                                     
 RESTART INCLUDES FLUIDS IN PLACE                                        
</message>
<message date="26/11/1976" time="2521.00000000000000">
 ******************************************                              
 * WELL VW1      HAS CHANGED TO           *                              
 * CONTROL BY OIL RATE                    *                              
 * FROM TIME   2521.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="26/12/1976" time="2551.00000000000000">
 ACTION ACT1 TRIGGERING ON NEXT                                          
 TIMESTEP. ACTION CONDITIONS MET ARE:                                    
 "ALWAYS"                                                                
</message>
<message date="26/12/1976" time="2551.00000000000000">
