<eclipse>
<error date="1/1/0" time="0.00000000000000">
 UNRECOGNISED KEYWORD ISGAS    IN RUNSPEC DATA                           
</error>
<error date="1/1/0" time="0.00000000000000">
 UNRECOGNISED KEYWORD COMPS    IN RUNSPEC DATA                           
</error>
<warning date="1/1/0" time="0.00000000000000">
 SPURIOUS DATA BEFORE TABDIMS  KEYWORD                                   
 6 /                                                                     
</warning>
<message date="1/1/1997" time="0.00000000000000">
 RESOPT   IS NOT AVAILABLE IN ECLIPSE 100                                
 AND HAS BEEN IGNORED                                                    
</message>
<message date="1/1/1997" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<error date="1/1/1997" time="0.00000000000000">
 LICENSE FAILURE: ERROR NUMBER IS -1                                     
</error>
</eclipse>
