<eclipse>
<warning date="1/1/0" time="0.00000000000000">
 AIM      METHOD IS NOT AVAILABLE IN ECLIPSE 100                         
 CHOICES ARE FULLY IMPLICIT (DEFAULT) OR IMPES                           
</warning>
<error date="1/1/0" time="0.00000000000000">
 UNRECOGNISED KEYWORD GEOMECH  IN RUNSPEC DATA                           
</error>
<warning date="1/1/0" time="0.00000000000000">
 SPURIOUS DATA BEFORE GEODIMS  KEYWORD                                   
  1* T FE RMBAL INIT /                                                   
</warning>
<error date="1/1/0" time="0.00000000000000">
 UNRECOGNISED KEYWORD GEODIMS  IN RUNSPEC DATA                           
</error>
<warning date="1/1/0" time="0.00000000000000">
 SPURIOUS DATA BEFORE COMPS    KEYWORD                                   
  1* 3 4 3 4 /                                                           
</warning>
<error date="1/1/0" time="0.00000000000000">
 UNRECOGNISED KEYWORD COMPS    IN RUNSPEC DATA                           
</error>
<warning date="1/1/0" time="0.00000000000000">
 SPURIOUS DATA BEFORE TABDIMS  KEYWORD                                   
 10 /                                                                    
</warning>
<message date="1/1/1990" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<error date="1/1/1990" time="0.00000000000000">
 LICENSE FAILURE: ERROR NUMBER IS -1                                     
</error>
</eclipse>
