<eclipse>
<message date="1/1/1983" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/1983" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
     102468 BYTES                                                        
</message>
<message date="1/1/1983" time="0.00000000000000">
 NEITHER OLDTRAN,OLDTRANR NOR NEWTRAN SPECIFIED                          
 TRANSMISSIBILITIES TO BE CALCULATED                                     
 USING  NEWTRAN                                                          
</message>
<comment date="1/1/1983" time="0.00000000000000">
 NO NON-NEIGHBOUR CONNECTIONS FOUND                                      
</comment>
<message date="1/1/1983" time="0.00000000000000">
 NUMBER OF ACTIVE CELLS IS 243                                           
</message>
<message date="1/1/1983" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SOLUTION SECTION IS                  
       1858 KBYTES                                                       
</message>
<message date="1/1/1983" time="0.00000000000000">
    58696 CHARACTER VARIABLES USED                                       
</message>
<warning date="1/1/1983" time="0.00000000000000">
 UNRECOGNISED MNEMONIC SOIL             IN DATA                          
 FOR KEYWORD RPTRST   IS IGNORED                                         
</warning>
<warning date="1/1/1983" time="0.00000000000000">
 UNRECOGNISED MNEMONIC SWAT             IN DATA                          
 FOR KEYWORD RPTRST   IS IGNORED                                         
</warning>
<warning date="1/1/1983" time="0.00000000000000">
 UNRECOGNISED MNEMONIC SGAS             IN DATA                          
 FOR KEYWORD RPTRST   IS IGNORED                                         
</warning>
<message date="1/1/1983" time="0.00000000000000">
 THE TOP-UP PHASE IS SET TO WATER AS                                     
 GROUP PL-A     HAS A TARGET OR LIMIT RESERVOIR                          
 VOLUME RATE OR VOIDAGE REPLACEMENT FRACTION                             
 FOR WATER INJECTION CONTROL                                             
</message>
<message date="1/1/1983" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/1983" time="0.00000000000000">
 DRSDT KEYWORD HAS NOT BEEN ENTERED, SO THE                              
 MAXIMUM GAS RE-SOLUTION RATE IS DEFAULTED TO INFINITY.                  
</message>
<message date="1/1/1983" time="0.00000000000000">
 GAS LIFT OPTIMISED AT TIME        0.00   DAYS                           
</message>
<message date="2/1/1983" time="1.00000000000000">
 GAS LIFT OPTIMISED AT TIME        1.00   DAYS                           
</message>
<message date="5/1/1983" time="4.00000000000000">
 GAS LIFT OPTIMISED AT TIME        4.00   DAYS                           
</message>
<message date="14/1/1983" time="13.00000000000000">
 GAS LIFT OPTIMISED AT TIME       13.00   DAYS                           
</message>
<message date="31/1/1983" time="30.00000000000000">
 RESTART FILE WRITTEN   REPORT     1                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="31/1/1983" time="30.00000000000000">
 GAS LIFT OPTIMISED AT TIME       30.00   DAYS                           
</message>
<message date="2/3/1983" time="60.00000000000000">
 RESTART FILE WRITTEN   REPORT     2                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="2/3/1983" time="60.00000000000000">
 GAS LIFT OPTIMISED AT TIME       60.00   DAYS                           
</message>
<message date="1/4/1983" time="90.00000000000000">
 RESTART FILE WRITTEN   REPORT     3                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="1/4/1983" time="90.00000000000000">
 GAS LIFT OPTIMISED AT TIME       90.00   DAYS                           
</message>
<message date="1/5/1983" time="120.00000000000000">
 RESTART FILE WRITTEN   REPORT     4                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="1/5/1983" time="120.00000000000000">
 GAS LIFT OPTIMISED AT TIME      120.00   DAYS                           
</message>
<message date="31/5/1983" time="150.00000000000000">
 RESTART FILE WRITTEN   REPORT     5                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="31/5/1983" time="150.00000000000000">
 GAS LIFT OPTIMISED AT TIME      150.00   DAYS                           
</message>
<message date="30/6/1983" time="180.00000000000000">
 RESTART FILE WRITTEN   REPORT     6                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="30/6/1983" time="180.00000000000000">
 GAS LIFT OPTIMISED AT TIME      180.00   DAYS                           
</message>
<message date="30/7/1983" time="210.00000000000000">
 RESTART FILE WRITTEN   REPORT     7                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="30/7/1983" time="210.00000000000000">
 GAS LIFT OPTIMISED AT TIME      210.00   DAYS                           
</message>
<message date="29/8/1983" time="240.00000000000000">
 RESTART FILE WRITTEN   REPORT     8                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="29/8/1983" time="240.00000000000000">
 GAS LIFT OPTIMISED AT TIME      240.00   DAYS                           
</message>
<message date="28/9/1983" time="270.00000000000000">
 RESTART FILE WRITTEN   REPORT     9                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="28/9/1983" time="270.00000000000000">
 GAS LIFT OPTIMISED AT TIME      270.00   DAYS                           
</message>
<message date="28/10/1983" time="300.00000000000000">
 RESTART FILE WRITTEN   REPORT    10                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="28/10/1983" time="300.00000000000000">
 GAS LIFT OPTIMISED AT TIME      300.00   DAYS                           
</message>
<message date="27/11/1983" time="330.00000000000000">
 RESTART FILE WRITTEN   REPORT    11                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="27/11/1983" time="330.00000000000000">
 GAS LIFT OPTIMISED AT TIME      330.00   DAYS                           
</message>
<message date="27/11/1983" time="330.00000000000000">
 ******************************************                              
 * WELL PB1      HAS CHANGED TO           *                              
 * CONTROL BY TUBING HEAD PRESSURE        *                              
 * FROM TIME    330.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="27/11/1983" time="330.00000000000000">
 ******************************************                              
 * WELL PB2      HAS CHANGED TO           *                              
 * CONTROL BY TUBING HEAD PRESSURE        *                              
 * FROM TIME    330.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="27/12/1983" time="360.00000000000000">
 RESTART FILE WRITTEN   REPORT    12                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="27/12/1983" time="360.00000000000000">
 GAS LIFT OPTIMISED AT TIME      360.00   DAYS                           
</message>
<warning date="27/12/1983" time="360.00000000000000">
 CURRENT WELL CONDITIONS REQUIRE THE EXTRAPOLATION                       
 OF AT LEAST ONE VFP TABLE. THE LAST                                     
 EXTRAPOLATION WAS A FLO VALUE OF   5.2323E+03                           
 IN VFP TABLE   1 BY FLOW IN WELL PC3                                    
</warning>
<message date="26/1/1984" time="390.00000000000000">
 RESTART FILE WRITTEN   REPORT    13                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="26/1/1984" time="390.00000000000000">
 GAS LIFT OPTIMISED AT TIME      390.00   DAYS                           
</message>
<warning date="26/1/1984" time="390.00000000000000">
 CURRENT WELL CONDITIONS REQUIRE THE EXTRAPOLATION                       
 OF AT LEAST ONE VFP TABLE. THE LAST                                     
 EXTRAPOLATION WAS A FLO VALUE OF   5.2980E+03                           
 IN VFP TABLE   1 BY FLOW IN WELL PA3                                    
</warning>
<message date="26/1/1984" time="390.00000000000000">
 ******************************************                              
 * WELL PA1      HAS CHANGED TO           *                              
 * CONTROL BY OIL RATE                    *                              
 * FROM TIME    390.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="26/1/1984" time="390.00000000000000">
 ******************************************                              
 * WELL PA3      HAS CHANGED TO           *                              
 * CONTROL BY OIL RATE                    *                              
 * FROM TIME    390.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="26/1/1984" time="390.00000000000000">
 ******************************************                              
 * WELL PC1      HAS CHANGED TO           *                              
 * CONTROL BY OIL RATE                    *                              
 * FROM TIME    390.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="26/1/1984" time="390.00000000000000">
 ******************************************                              
 * WELL PC3      HAS CHANGED TO           *                              
 * CONTROL BY OIL RATE                    *                              
 * FROM TIME    390.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="26/1/1984" time="390.00000000000000">
 **********************************                                      
 * GROUP FIELD    CANNOT MEET ITS *                                      
 *  OIL   PRODUCTION TARGET       *                                      
 * AFTER TIME    390.00   DAYS  . *                                      
 **********************************                                      
</message>
<message date="25/2/1984" time="420.00000000000000">
 RESTART FILE WRITTEN   REPORT    14                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="25/2/1984" time="420.00000000000000">
 GAS LIFT OPTIMISED AT TIME      420.00   DAYS                           
</message>
<warning date="25/2/1984" time="420.00000000000000">
 CURRENT WELL CONDITIONS REQUIRE THE EXTRAPOLATION                       
 OF AT LEAST ONE VFP TABLE. THE LAST                                     
 EXTRAPOLATION WAS A FLO VALUE OF   5.3325E+03                           
 IN VFP TABLE   1 BY FLOW IN WELL PA3                                    
</warning>
<message date="26/3/1984" time="450.00000000000000">
 RESTART FILE WRITTEN   REPORT    15                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="26/3/1984" time="450.00000000000000">
 GAS LIFT OPTIMISED AT TIME      450.00   DAYS                           
</message>
<warning date="26/3/1984" time="450.00000000000000">
 CURRENT WELL CONDITIONS REQUIRE THE EXTRAPOLATION                       
 OF AT LEAST ONE VFP TABLE. THE LAST                                     
 EXTRAPOLATION WAS A FLO VALUE OF   5.3736E+03                           
 IN VFP TABLE   1 BY FLOW IN WELL PA3                                    
</warning>
<message date="25/4/1984" time="480.00000000000000">
 RESTART FILE WRITTEN   REPORT    16                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="25/4/1984" time="480.00000000000000">
 GAS LIFT OPTIMISED AT TIME      480.00   DAYS                           
</message>
<warning date="25/4/1984" time="480.00000000000000">
 CURRENT WELL CONDITIONS REQUIRE THE EXTRAPOLATION                       
 OF AT LEAST ONE VFP TABLE. THE LAST                                     
 EXTRAPOLATION WAS A FLO VALUE OF   5.0874E+03                           
 IN VFP TABLE   1 BY FLOW IN WELL PC3                                    
</warning>
<message date="25/4/1984" time="480.00000000000000">
 ******************************************                              
 * WELL PA3      HAS CHANGED TO           *                              
 * CONTROL BY TUBING HEAD PRESSURE        *                              
 * FROM TIME    480.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="25/4/1984" time="480.00000000000000">
 ******************************************                              
 * WELL PC3      HAS CHANGED TO           *                              
 * CONTROL BY TUBING HEAD PRESSURE        *                              
 * FROM TIME    480.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="25/5/1984" time="510.00000000000000">
 RESTART FILE WRITTEN   REPORT    17                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="25/5/1984" time="510.00000000000000">
 GAS LIFT OPTIMISED AT TIME      510.00   DAYS                           
</message>
<warning date="25/5/1984" time="510.00000000000000">
 CURRENT WELL CONDITIONS REQUIRE THE EXTRAPOLATION                       
 OF AT LEAST ONE VFP TABLE. THE LAST                                     
 EXTRAPOLATION WAS A GFR VALUE OF   4.2823E-01                           
 IN VFP TABLE   1 BY FLOW IN WELL PB1                                    
</warning>
<message date="25/5/1984" time="510.00000000000000">
 ******************************************                              
 * WELL PA1      HAS CHANGED TO           *                              
 * CONTROL BY TUBING HEAD PRESSURE        *                              
 * FROM TIME    510.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="25/5/1984" time="510.00000000000000">
 ******************************************                              
 * WELL PC1      HAS CHANGED TO           *                              
 * CONTROL BY TUBING HEAD PRESSURE        *                              
 * FROM TIME    510.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="24/6/1984" time="540.00000000000000">
 RESTART FILE WRITTEN   REPORT    18                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="24/6/1984" time="540.00000000000000">
 GAS LIFT OPTIMISED AT TIME      540.00   DAYS                           
</message>
<warning date="24/6/1984" time="540.00000000000000">
 CURRENT WELL CONDITIONS REQUIRE THE EXTRAPOLATION                       
 OF AT LEAST ONE VFP TABLE. THE LAST                                     
 EXTRAPOLATION WAS A GFR VALUE OF   4.2616E-01                           
 IN VFP TABLE   1 BY FLOW IN WELL PB1                                    
</warning>
<message date="24/7/1984" time="570.00000000000000">
 RESTART FILE WRITTEN   REPORT    19                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="24/7/1984" time="570.00000000000000">
 GAS LIFT OPTIMISED AT TIME      570.00   DAYS                           
</message>
<warning date="24/7/1984" time="570.00000000000000">
 CURRENT WELL CONDITIONS REQUIRE THE EXTRAPOLATION                       
 OF AT LEAST ONE VFP TABLE. THE LAST                                     
 EXTRAPOLATION WAS A GFR VALUE OF   4.2449E-01                           
 IN VFP TABLE   1 BY FLOW IN WELL PB1                                    
</warning>
<message date="23/8/1984" time="600.00000000000000">
 RESTART FILE WRITTEN   REPORT    20                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="23/8/1984" time="600.00000000000000">
 GAS LIFT OPTIMISED AT TIME      600.00   DAYS                           
</message>
<warning date="23/8/1984" time="600.00000000000000">
 CURRENT WELL CONDITIONS REQUIRE THE EXTRAPOLATION                       
 OF AT LEAST ONE VFP TABLE. THE LAST                                     
 EXTRAPOLATION WAS A FLO VALUE OF   5.1019E+03                           
 IN VFP TABLE   1 BY FLOW IN WELL PC3                                    
</warning>
<message date="23/8/1984" time="600.00000000000000">
 ******************************************                              
 * WELL PC1      HAS CHANGED TO           *                              
 * CONTROL BY OIL RATE                    *                              
 * FROM TIME    600.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="22/9/1984" time="630.00000000000000">
 RESTART FILE WRITTEN   REPORT    21                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="22/9/1984" time="630.00000000000000">
 GAS LIFT OPTIMISED AT TIME      630.00   DAYS                           
</message>
<warning date="22/9/1984" time="630.00000000000000">
 WELL PB1      CANNOT PRODUCE AT THE REQUIRED T.H.P.                     
</warning>
<message date="22/9/1984" time="630.00000000000000">
 WELL PB1      CANNOT OPERATE UNDER THE CURRENT                          
 RESERVOIR CONDITIONS IN NON-LINEAR ITERATION   1.                       
 ITS IPR IS    Q(P)  =  A  -  BHP * B ,   WHERE:                         
 A(O,W,G) =   9.8130E+04  2.9028E+02  4.1301E+04                         
 B(O,W,G) =   4.6355E+01  1.3712E-01  1.9510E+01 .                       
 LAST CONVERGED SOLUTION:                                                
     ORAT        WRAT        GRAT        BHP         THP                 
   1.3540E+03  3.9032E+00  5.7212E+02  2.0962E+03  5.0000E+02            
 THE WELL IS   SHUT  FOR THE ITERATION.                                  
</message>
<message date="22/9/1984" time="630.00000000000000">
 WELL PB1      IS REVIVED FOR ITERATION   2                              
</message>
<warning date="22/9/1984" time="630.00000000000000">
 WELL PB1      CANNOT PRODUCE AT THE REQUIRED T.H.P.                     
</warning>
<message date="22/9/1984" time="630.00000000000000">
 WELL PB1      CANNOT OPERATE UNDER THE CURRENT                          
 RESERVOIR CONDITIONS IN NON-LINEAR ITERATION   3.                       
 ITS IPR IS    Q(P)  =  A  -  BHP * B ,   WHERE:                         
 A(O,W,G) =   9.8206E+04  2.9028E+02  4.1338E+04                         
 B(O,W,G) =   4.6368E+01  1.3704E-01  1.9517E+01 .                       
 LAST CONVERGED SOLUTION:                                                
     ORAT        WRAT        GRAT        BHP         THP                 
   1.5589E+03  4.4703E+00  6.5994E+02  2.0965E+03  5.0000E+02            
 THE WELL IS   SHUT  FOR THE ITERATION.                                  
</message>
<warning date="22/9/1984" time="630.00000000000000">
 CURRENT WELL CONDITIONS REQUIRE THE EXTRAPOLATION                       
 OF AT LEAST ONE VFP TABLE. THE LAST                                     
 EXTRAPOLATION WAS A FLO VALUE OF   5.0115E+03                           
 IN VFP TABLE   1 BY FLOW IN WELL PC1                                    
</warning>
<message date="22/9/1984" time="630.00000000000000">
 ****************************************************************        
 * WELL PB1      IS  SHUT   AT TIME     630.00   DAYS   BECAUSE *        
 * IT CANNOT OPERATE AT CURRENT RESERVOIR CONDITIONS.           *        
 ****************************************************************        
</message>
<message date="22/10/1984" time="660.00000000000000">
 RESTART FILE WRITTEN   REPORT    22                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="22/10/1984" time="660.00000000000000">
 GAS LIFT OPTIMISED AT TIME      660.00   DAYS                           
</message>
<warning date="22/10/1984" time="660.00000000000000">
 CURRENT WELL CONDITIONS REQUIRE THE EXTRAPOLATION                       
 OF AT LEAST ONE VFP TABLE. THE LAST                                     
 EXTRAPOLATION WAS A FLO VALUE OF   5.0124E+03                           
 IN VFP TABLE   1 BY FLOW IN WELL PC1                                    
</warning>
<message date="21/11/1984" time="690.00000000000000">
 RESTART FILE WRITTEN   REPORT    23                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="21/11/1984" time="690.00000000000000">
 GAS LIFT OPTIMISED AT TIME      690.00   DAYS                           
</message>
<warning date="21/11/1984" time="690.00000000000000">
 CURRENT WELL CONDITIONS REQUIRE THE EXTRAPOLATION                       
 OF AT LEAST ONE VFP TABLE. THE LAST                                     
 EXTRAPOLATION WAS A GFR VALUE OF   4.2819E-01                           
 IN VFP TABLE   1 BY FLOW IN WELL PC1                                    
</warning>
<message date="21/12/1984" time="720.00000000000000">
 RESTART FILE WRITTEN   REPORT    24                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="21/12/1984" time="720.00000000000000">
 GAS LIFT OPTIMISED AT TIME      720.00   DAYS                           
</message>
<warning date="21/12/1984" time="720.00000000000000">
 CURRENT WELL CONDITIONS REQUIRE THE EXTRAPOLATION                       
 OF AT LEAST ONE VFP TABLE. THE LAST                                     
 EXTRAPOLATION WAS A GFR VALUE OF   4.2743E-01                           
 IN VFP TABLE   1 BY FLOW IN WELL PA1                                    
</warning>
<message date="21/12/1984" time="720.00000000000000">
 ******************************************                              
 * WELL PC1      HAS CHANGED TO           *                              
 * CONTROL BY TUBING HEAD PRESSURE        *                              
 * FROM TIME    720.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="20/1/1985" time="750.00000000000000">
 RESTART FILE WRITTEN   REPORT    25                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="20/1/1985" time="750.00000000000000">
 GAS LIFT OPTIMISED AT TIME      750.00   DAYS                           
</message>
<warning date="20/1/1985" time="750.00000000000000">
 CURRENT WELL CONDITIONS REQUIRE THE EXTRAPOLATION                       
 OF AT LEAST ONE VFP TABLE. THE LAST                                     
 EXTRAPOLATION WAS A GFR VALUE OF   4.2446E-01                           
 IN VFP TABLE   1 BY FLOW IN WELL PA1                                    
</warning>
<message date="19/2/1985" time="780.00000000000000">
 RESTART FILE WRITTEN   REPORT    26                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="19/2/1985" time="780.00000000000000">
 GAS LIFT OPTIMISED AT TIME      780.00   DAYS                           
</message>
<warning date="19/2/1985" time="780.00000000000000">
 CURRENT WELL CONDITIONS REQUIRE THE EXTRAPOLATION                       
 OF AT LEAST ONE VFP TABLE. THE LAST                                     
 EXTRAPOLATION WAS A GFR VALUE OF   4.2169E-01                           
 IN VFP TABLE   1 BY FLOW IN WELL PA1                                    
</warning>
<message date="21/3/1985" time="810.00000000000000">
 RESTART FILE WRITTEN   REPORT    27                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="21/3/1985" time="810.00000000000000">
 GAS LIFT OPTIMISED AT TIME      810.00   DAYS                           
</message>
<warning date="21/3/1985" time="810.00000000000000">
 CURRENT WELL CONDITIONS REQUIRE THE EXTRAPOLATION                       
 OF AT LEAST ONE VFP TABLE. THE LAST                                     
 EXTRAPOLATION WAS A GFR VALUE OF   4.1907E-01                           
 IN VFP TABLE   1 BY FLOW IN WELL PA1                                    
</warning>
<message date="20/4/1985" time="840.00000000000000">
 RESTART FILE WRITTEN   REPORT    28                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="20/4/1985" time="840.00000000000000">
 GAS LIFT OPTIMISED AT TIME      840.00   DAYS                           
</message>
<warning date="20/4/1985" time="840.00000000000000">
 CURRENT WELL CONDITIONS REQUIRE THE EXTRAPOLATION                       
 OF AT LEAST ONE VFP TABLE. THE LAST                                     
 EXTRAPOLATION WAS A GFR VALUE OF   4.2456E-01                           
 IN VFP TABLE   1 BY FLOW IN WELL PA1                                    
</warning>
<warning date="20/4/1985" time="840.00000000000000">
 WELL PB1      CHANGED TO EXPLICIT WATER CUT                             
 AND GOR FOR VFP TABLE LOOK-UP,                                          
 TO PREVENT PREMATURE CLOSURE.                                           
</warning>
<message date="20/5/1985" time="870.00000000000000">
 RESTART FILE WRITTEN   REPORT    29                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="20/5/1985" time="870.00000000000000">
 GAS LIFT OPTIMISED AT TIME      870.00   DAYS                           
</message>
<warning date="20/5/1985" time="870.00000000000000">
 CURRENT WELL CONDITIONS REQUIRE THE EXTRAPOLATION                       
 OF AT LEAST ONE VFP TABLE. THE LAST                                     
 EXTRAPOLATION WAS A GFR VALUE OF   4.2905E-01                           
 IN VFP TABLE   1 BY FLOW IN WELL PA1                                    
</warning>
<message date="19/6/1985" time="900.00000000000000">
 RESTART FILE WRITTEN   REPORT    30                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="19/6/1985" time="900.00000000000000">
 GAS LIFT OPTIMISED AT TIME      900.00   DAYS                           
</message>
<warning date="19/6/1985" time="900.00000000000000">
 CURRENT WELL CONDITIONS REQUIRE THE EXTRAPOLATION                       
 OF AT LEAST ONE VFP TABLE. THE LAST                                     
 EXTRAPOLATION WAS A GFR VALUE OF   4.2795E-01                           
 IN VFP TABLE   1 BY FLOW IN WELL PA3                                    
</warning>
<message date="19/7/1985" time="930.00000000000000">
 RESTART FILE WRITTEN   REPORT    31                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="19/7/1985" time="930.00000000000000">
 GAS LIFT OPTIMISED AT TIME      930.00   DAYS                           
</message>
<warning date="19/7/1985" time="930.00000000000000">
 CURRENT WELL CONDITIONS REQUIRE THE EXTRAPOLATION                       
 OF AT LEAST ONE VFP TABLE. THE LAST                                     
 EXTRAPOLATION WAS A GFR VALUE OF   4.2619E-01                           
 IN VFP TABLE   1 BY FLOW IN WELL PA3                                    
</warning>
<message date="18/8/1985" time="960.00000000000000">
 RESTART FILE WRITTEN   REPORT    32                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="18/8/1985" time="960.00000000000000">
 GAS LIFT OPTIMISED AT TIME      960.00   DAYS                           
</message>
<warning date="18/8/1985" time="960.00000000000000">
 CURRENT WELL CONDITIONS REQUIRE THE EXTRAPOLATION                       
 OF AT LEAST ONE VFP TABLE. THE LAST                                     
 EXTRAPOLATION WAS A GFR VALUE OF   4.2455E-01                           
 IN VFP TABLE   1 BY FLOW IN WELL PA3                                    
</warning>
<message date="17/9/1985" time="990.00000000000000">
 RESTART FILE WRITTEN   REPORT    33                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="17/9/1985" time="990.00000000000000">
 GAS LIFT OPTIMISED AT TIME      990.00   DAYS                           
</message>
<warning date="17/9/1985" time="990.00000000000000">
 CURRENT WELL CONDITIONS REQUIRE THE EXTRAPOLATION                       
 OF AT LEAST ONE VFP TABLE. THE LAST                                     
 EXTRAPOLATION WAS A GFR VALUE OF   4.2298E-01                           
 IN VFP TABLE   1 BY FLOW IN WELL PA3                                    
</warning>
<message date="17/10/1985" time="1020.00000000000000">
 RESTART FILE WRITTEN   REPORT    34                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="17/10/1985" time="1020.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1020.00   DAYS                           
</message>
<message date="16/11/1985" time="1050.00000000000000">
 RESTART FILE WRITTEN   REPORT    35                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="16/11/1985" time="1050.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1050.00   DAYS                           
</message>
<message date="16/12/1985" time="1080.00000000000000">
 RESTART FILE WRITTEN   REPORT    36                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="16/12/1985" time="1080.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1080.00   DAYS                           
</message>
<message date="15/1/1986" time="1110.00000000000000">
 RESTART FILE WRITTEN   REPORT    37                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="15/1/1986" time="1110.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1110.00   DAYS                           
</message>
<message date="14/2/1986" time="1140.00000000000000">
 RESTART FILE WRITTEN   REPORT    38                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="14/2/1986" time="1140.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1140.00   DAYS                           
</message>
<message date="16/3/1986" time="1170.00000000000000">
 RESTART FILE WRITTEN   REPORT    39                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="16/3/1986" time="1170.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1170.00   DAYS                           
</message>
<message date="15/4/1986" time="1200.00000000000000">
 RESTART FILE WRITTEN   REPORT    40                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="15/4/1986" time="1200.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1200.00   DAYS                           
</message>
<message date="15/5/1986" time="1230.00000000000000">
 RESTART FILE WRITTEN   REPORT    41                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="15/5/1986" time="1230.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1230.00   DAYS                           
</message>
<message date="14/6/1986" time="1260.00000000000000">
 RESTART FILE WRITTEN   REPORT    42                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="14/6/1986" time="1260.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1260.00   DAYS                           
</message>
<message date="14/7/1986" time="1290.00000000000000">
 RESTART FILE WRITTEN   REPORT    43                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="14/7/1986" time="1290.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1290.00   DAYS                           
</message>
<message date="13/8/1986" time="1320.00000000000000">
 RESTART FILE WRITTEN   REPORT    44                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="13/8/1986" time="1320.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1320.00   DAYS                           
</message>
<message date="12/9/1986" time="1350.00000000000000">
 RESTART FILE WRITTEN   REPORT    45                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="12/9/1986" time="1350.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1350.00   DAYS                           
</message>
<message date="12/10/1986" time="1380.00000000000000">
 RESTART FILE WRITTEN   REPORT    46                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="12/10/1986" time="1380.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1380.00   DAYS                           
</message>
<message date="11/11/1986" time="1410.00000000000000">
 RESTART FILE WRITTEN   REPORT    47                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="11/11/1986" time="1410.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1410.00   DAYS                           
</message>
<message date="11/12/1986" time="1440.00000000000000">
 RESTART FILE WRITTEN   REPORT    48                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="11/12/1986" time="1440.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1440.00   DAYS                           
</message>
<message date="10/1/1987" time="1470.00000000000000">
 RESTART FILE WRITTEN   REPORT    49                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="10/1/1987" time="1470.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1470.00   DAYS                           
</message>
<message date="9/2/1987" time="1500.00000000000000">
 RESTART FILE WRITTEN   REPORT    50                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="9/2/1987" time="1500.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1500.00   DAYS                           
</message>
<message date="11/3/1987" time="1530.00000000000000">
 RESTART FILE WRITTEN   REPORT    51                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="11/3/1987" time="1530.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1530.00   DAYS                           
</message>
<message date="10/4/1987" time="1560.00000000000000">
 RESTART FILE WRITTEN   REPORT    52                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="10/4/1987" time="1560.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1560.00   DAYS                           
</message>
<message date="10/5/1987" time="1590.00000000000000">
 RESTART FILE WRITTEN   REPORT    53                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="10/5/1987" time="1590.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1590.00   DAYS                           
</message>
<message date="9/6/1987" time="1620.00000000000000">
 RESTART FILE WRITTEN   REPORT    54                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="9/6/1987" time="1620.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1620.00   DAYS                           
</message>
<message date="9/7/1987" time="1650.00000000000000">
 RESTART FILE WRITTEN   REPORT    55                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="9/7/1987" time="1650.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1650.00   DAYS                           
</message>
<message date="8/8/1987" time="1680.00000000000000">
 RESTART FILE WRITTEN   REPORT    56                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="8/8/1987" time="1680.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1680.00   DAYS                           
</message>
<message date="7/9/1987" time="1710.00000000000000">
 RESTART FILE WRITTEN   REPORT    57                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="7/9/1987" time="1710.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1710.00   DAYS                           
</message>
<message date="7/10/1987" time="1740.00000000000000">
 RESTART FILE WRITTEN   REPORT    58                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="7/10/1987" time="1740.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1740.00   DAYS                           
</message>
<message date="6/11/1987" time="1770.00000000000000">
 RESTART FILE WRITTEN   REPORT    59                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="6/11/1987" time="1770.00000000000000">
 GAS LIFT OPTIMISED AT TIME     1770.00   DAYS                           
</message>
<message date="6/12/1987" time="1800.00000000000000">
 RESTART FILE WRITTEN   REPORT    60                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
</eclipse>
