<eclipse>
<warning date="1/1/0" time="0.00000000000000">
  NODPCO HAS NO EFFECT IN ECLIPSE 100                                    
</warning>
<error date="1/1/2005" time="0.00000000000000">
 DISSOLVED GAS IN LIVE OIL IS REQUESTED, BUT                             
 THE OIL AND GAS PHASES ARE NOT BOTH DECLARED                            
 PRESENT.  THE OPTION IS SWITCHED OFF.                                   
</error>
<message date="1/1/2005" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<error date="1/1/2005" time="0.00000000000000">
 LICENSE FAILURE: ERROR NUMBER IS -1                                     
</error>
</eclipse>
