<eclipse>
<message date="6/12/1987" time="0.00000000000000">
 RESOPT   IS NOT AVAILABLE IN ECLIPSE 100                                
 AND HAS BEEN IGNORED                                                    
</message>
<message date="6/12/1987" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="6/12/1987" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
     668076 BYTES                                                        
</message>
<message date="6/12/1987" time="0.00000000000000">
 NEITHER OLDTRAN,OLDTRANR NOR NEWTRAN SPECIFIED                          
 TRANSMISSIBILITIES TO BE CALCULATED                                     
 USING  NEWTRAN                                                          
</message>
<comment date="6/12/1987" time="0.00000000000000">
 NO NON-NEIGHBOUR CONNECTIONS FOUND                                      
</comment>
<message date="6/12/1987" time="0.00000000000000">
 NUMBER OF ACTIVE CELLS IS 1680                                          
</message>
<message date="6/12/1987" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SOLUTION SECTION IS                  
       2409 KBYTES                                                       
</message>
<message date="6/12/1987" time="0.00000000000000">
    58542 CHARACTER VARIABLES USED                                       
</message>
<error date="6/12/1987" time="0.00000000000000">
 ERROR IN SOF3 TABLE NUMBER   1                                          
 TOO MUCH DATA - A MAXIMUM OF  20 ROWS WAS EXPECTED                      
</error>
<error date="6/12/1987" time="0.00000000000000">
 ERROR IN SOF3 TABLE NUMBER   1                                          
 AT THE MAXIMUM OIL SATURATION ( 0.7622)                                 
 KROW AND KROG SHOULD BOTH EQUAL THE OIL RELATIVE                        
 PERMEABILITY FOR A SYSTEM WITH OIL AND CONNATE                          
 WATER ONLY - BUT IN THIS CASE THEY ARE DIFFERENT                        
  ( KROW = 0.6900 AND KROG = 0.2300)                                     
</error>
<warning date="6/12/1987" time="0.00000000000000">
 SPURIOUS DATA BEFORE PVTW     KEYWORD                                   
     0.823723   0.8400000   1*                                           
     0.854486   0.9000000   1*                                           
     0.885248   1.0000000   1.0000000                                    
 /   END OF TABLE10                                                      
</warning>
<warning date="6/12/1987" time="0.00000000000000">
 INCONSISTENT END POINTS IN SATURATION TABLE   1                         
 THE MAXIMUM OIL SATURATION (0.7622)                                     
 PLUS THE CONNATE WATER SATURATION (0.1148)                              
 PLUS THE CONNATE GAS SATURATION (0.0000)                                
</warning>
<error date="6/12/1987" time="0.00000000000000">
 RVVD/PDVD SHOULD ONLY BE SPECIFIED IF THERE                             
 IS WET GAS CONTAINING VAPOURISED OIL                                    
</error>
<warning date="6/12/1987" time="0.00000000000000">
 SPURIOUS DATA BEFORE SUMMARY  KEYWORD                                   
   600 0                                                                 
    0  0                                                                 
 /                                                                       
</warning>
<warning date="6/12/1987" time="0.00000000000000">
 UNRECOGNISED MNEMONIC SOIL             IN DATA                          
 FOR KEYWORD RPTRST   IS IGNORED                                         
</warning>
<warning date="6/12/1987" time="0.00000000000000">
 UNRECOGNISED MNEMONIC SWAT             IN DATA                          
 FOR KEYWORD RPTRST   IS IGNORED                                         
</warning>
<warning date="6/12/1987" time="0.00000000000000">
 UNRECOGNISED MNEMONIC SGAS             IN DATA                          
 FOR KEYWORD RPTRST   IS IGNORED                                         
</warning>
<warning date="6/12/1987" time="0.00000000000000">
 THE BOTTOM HOLE PRESSURE LIMIT FOR WELL GI                              
 HAS BEEN DEFAULTED. THE DEFAULT VALUE IS    6891.   BARSA               
</warning>
<message date="6/12/1987" time="0.00000000000000">
 THE TOP-UP PHASE IS SET TO  GAS  AS                                     
 GROUP CSW      HAS A TARGET OR LIMIT RESERVOIR                          
 VOLUME RATE OR VOIDAGE REPLACEMENT FRACTION                             
 FOR  GAS  INJECTION CONTROL                                             
</message>
<message date="6/12/1987" time="0.00000000000000">
 DRSDT KEYWORD HAS NOT BEEN ENTERED, SO THE                              
 MAXIMUM GAS RE-SOLUTION RATE IS DEFAULTED TO INFINITY.                  
</message>
<error date="14/1/1992" time="1500.00000000000000">
 UNRECOGNISED KEYWORD OPTIMIZE IN SCHEDULING DATA                        
</error>
<error date="14/1/1992" time="1500.00000000000000">
 UNRECOGNISED KEYWORD OPTDIMS  IN SCHEDULING DATA                        
</error>
<warning date="14/1/1992" time="1500.00000000000000">
 SPURIOUS DATA BEFORE OPTTUNE  KEYWORD                                   
  20 100 /                                                               
</warning>
<error date="14/1/1992" time="1500.00000000000000">
 UNRECOGNISED KEYWORD OPTTUNE  IN SCHEDULING DATA                        
</error>
<warning date="14/1/1992" time="1500.00000000000000">
 SPURIOUS DATA BEFORE OPTFUNC  KEYWORD                                   
  0.05 /                                                                 
</warning>
<error date="14/1/1992" time="1500.00000000000000">
 UNRECOGNISED KEYWORD OPTFUNC  IN SCHEDULING DATA                        
</error>
<warning date="14/1/1992" time="1500.00000000000000">
 SPURIOUS DATA BEFORE OPTPARS  KEYWORD                                   
  'FOPT' 'FIELD' /                                                       
 /                                                                       
</warning>
<error date="14/1/1992" time="1500.00000000000000">
 UNRECOGNISED KEYWORD OPTPARS  IN SCHEDULING DATA                        
</error>
<warning date="14/1/1992" time="1500.00000000000000">
 SPURIOUS DATA BEFORE OPTCONS  KEYWORD                                   
  'WBHP' 'P1' 100.0 350.0 /                                              
  'WBHP' 'P2' 100.0 350.0 /                                              
 /                                                                       
</warning>
<error date="14/1/1992" time="1500.00000000000000">
 UNRECOGNISED KEYWORD OPTCONS  IN SCHEDULING DATA                        
</error>
<warning date="14/1/1992" time="1500.00000000000000">
 SPURIOUS DATA BEFORE END      KEYWORD                                   
  'FOPR' 'FIELD' '&lt;' 3015 /                                           
  'FGPR' 'FIELD' '&lt;' 665000 /                                         
 /                                                                       
</warning>
</eclipse>
