<eclipse>
<message date="1/9/1990" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/9/1990" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
      43464 BYTES                                                        
</message>
<message date="1/9/1990" time="0.00000000000000">
 NEITHER OLDTRAN,OLDTRANR NOR NEWTRAN SPECIFIED                          
 BLOCK CENTRE TRANSMISSIBILITIES TO BE CALCULATED                        
 USING  OLDTRAN                                                          
</message>
<comment date="1/9/1990" time="0.00000000000000">
 NO NON-NEIGHBOUR CONNECTIONS FOUND                                      
</comment>
<message date="1/9/1990" time="0.00000000000000">
 NUMBER OF ACTIVE CELLS IS 81                                            
</message>
<message date="1/9/1990" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SOLUTION SECTION IS                  
     356444 BYTES                                                        
</message>
<message date="1/9/1990" time="0.00000000000000">
    58647 CHARACTER VARIABLES USED                                       
</message>
<warning date="1/9/1990" time="0.00000000000000">
 INCONSISTENT END POINTS IN SATURATION TABLE   1                         
 THE MAXIMUM GAS SATURATION (1.0000)                                     
 PLUS THE CONNATE WATER SATURATION (0.1800)                              
 MUST NOT EXCEED 1.0                                                     
</warning>
<warning date="1/9/1990" time="0.00000000000000">
 INCONSISTENT END POINTS IN SATURATION TABLE   1                         
 THE MAXIMUM WATER SATURATION (1.0000)                                   
 PLUS THE CONNATE GAS SATURATION (0.3820)                                
 MUST NOT EXCEED 1.0                                                     
</warning>
<warning date="1/9/1990" time="0.00000000000000">
 SPURIOUS DATA BEFORE WBHP     KEYWORD                                   
 'P13' /                                                                 
 'P31' /                                                                 
 'P33' /                                                                 
 'I22' /                                                                 
</warning>
<warning date="1/9/1990" time="0.00000000000000">
 THE PREFERRED PHASE FOR WELL I22      IS RE-SET                         
 TO WATER FLOW, TO MATCH THE INJECTED PHASE.                             
</warning>
<message date="16/10/1990" time="45.13162319512586">
 ******************************************                              
 * WELL I22      HAS CHANGED TO           *                              
 * CONTROL BY BOTTOM HOLE PRESSURE        *                              
 * FROM TIME     45.13   DAYS  .          *                              
 ******************************************                              
</message>
<message date="20/12/1990" time="110.00000000000000">
 ******************************************                              
 * WELL P13      HAS CHANGED TO           *                              
 * CONTROL BY BOTTOM HOLE PRESSURE        *                              
 * FROM TIME    110.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="20/12/1990" time="110.00000000000000">
 ******************************************                              
 * WELL P31      HAS CHANGED TO           *                              
 * CONTROL BY BOTTOM HOLE PRESSURE        *                              
 * FROM TIME    110.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="20/12/1990" time="110.00000000000000">
 ******************************************                              
 * WELL P33      HAS CHANGED TO           *                              
 * CONTROL BY BOTTOM HOLE PRESSURE        *                              
 * FROM TIME    110.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="16/10/1991" time="410.00000000000000">
 ******************************************                              
 * WELL P11      HAS CHANGED TO           *                              
 * CONTROL BY BOTTOM HOLE PRESSURE        *                              
 * FROM TIME    410.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="4/1/1992" time="490.00000000000000">
 ******************************************                              
 * WELL I22      HAS CHANGED TO           *                              
 * CONTROL BY RESERVOIR FLUID VOLUME RATE *                              
 * FROM TIME    490.00   DAYS  .          *                              
 ******************************************                              
</message>
</eclipse>
