<eclipse>
<warning date="1/1/0" time="0.00000000000000">
 SPURIOUS DATA BEFORE TITLE    KEYWORD                                   
           THIS SECTION SETS UP THE BASICS FOR THE SIMULATION            
</warning>
<message date="1/1/1983" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<error date="1/1/1983" time="0.00000000000000">
 LICENSE FAILURE: ERROR NUMBER IS -1                                     
</error>
</eclipse>
