<eclipse>
<message date="1/1/1983" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/1983" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
      22376 BYTES                                                        
</message>
<warning date="1/1/1983" time="0.00000000000000">
 SPURIOUS DATA BEFORE DEBUG    KEYWORD                                   
 /                                                                       
</warning>
<warning date="1/1/1983" time="0.00000000000000">
 PERMZ KEYWORD HAS NOT BEEN SPECIFIED FOR THIS                           
 2D AREAL MODEL.  PLEASE RE-CHECK DATA INPUT                             
</warning>
<message date="1/1/1983" time="0.00000000000000">
 NEITHER OLDTRAN,OLDTRANR NOR NEWTRAN SPECIFIED                          
 BLOCK CENTRE TRANSMISSIBILITIES TO BE CALCULATED                        
 USING  OLDTRAN                                                          
</message>
<comment date="1/1/1983" time="0.00000000000000">
 NO NON-NEIGHBOUR CONNECTIONS FOUND                                      
</comment>
<message date="1/1/1983" time="0.00000000000000">
 NUMBER OF ACTIVE CELLS IS 25                                            
</message>
<message date="1/1/1983" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SOLUTION SECTION IS                  
     242732 BYTES                                                        
</message>
<message date="1/1/1983" time="0.00000000000000">
    58535 CHARACTER VARIABLES USED                                       
</message>
<warning date="1/1/1983" time="0.00000000000000">
 THE BOTTOM HOLE PRESSURE LIMIT FOR WELL I                               
 HAS BEEN DEFAULTED. THE DEFAULT VALUE IS  100000.   PSIA                
</warning>
<warning date="1/1/1983" time="0.00000000000000">
 THE BOTTOM HOLE PRESSURE LIMIT FOR WELL I                               
 HAS BEEN DEFAULTED. THE DEFAULT VALUE IS  100000.   PSIA                
</warning>
</eclipse>
