<eclipse>
<error date="1/1/2007" time="0.00000000000000">
 UNRECOGNISED KEYWORD COMPS    IN RUNSPEC DATA                           
</error>
<warning date="1/1/2007" time="0.00000000000000">
 SPURIOUS DATA BEFORE EQLDIMS  KEYWORD                                   
 7 /                                                                     
</warning>
<error date="1/1/2007" time="0.00000000000000">
 KEYWORD ENDSCALE                                                        
 ENCOUNTERED WHILE READING SECTION    1 OF KEYWORD MISCIBLE              
 USUALLY CAUSED BY MISSING SLASH ( / )                                   
</error>
<error date="1/1/2007" time="0.00000000000000">
 KEYWORD GRID                                                            
 ENCOUNTERED WHILE READING SECTION    1 OF KEYWORD ENDSCALE              
 USUALLY CAUSED BY MISSING SLASH ( / )                                   
</error>
<warning date="1/1/2007" time="0.00000000000000">
 UNRECOGNISED MNEMONIC UNIFIN   IN KEYWORD ENDSCALE                      
</warning>
<warning date="1/1/2007" time="0.00000000000000">
 UNRECOGNISED MNEMONIC UNIFOUT  IN KEYWORD ENDSCALE                      
</warning>
<message date="1/1/2007" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<error date="1/1/2007" time="0.00000000000000">
 LICENSE FAILURE: ERROR NUMBER IS -1                                     
</error>
</eclipse>
