<eclipse>
<error date="1/1/2007" time="0.00000000000000">
 UNRECOGNISED KEYWORD COMPS    IN RUNSPEC DATA                           
</error>
<warning date="1/1/2007" time="0.00000000000000">
 SPURIOUS DATA BEFORE DIMENS   KEYWORD                                   
 10 /                                                                    
</warning>
<error date="1/1/2007" time="0.00000000000000">
 UNRECOGNISED KEYWORD FMTSAVE  IN RUNSPEC DATA                           
</error>
<error date="1/1/2007" time="0.00000000000000">
 UNRECOGNISED KEYWORD NODPCDT  IN RUNSPEC DATA                           
</error>
<warning date="1/1/2007" time="0.00000000000000">
 UNRECOGNISED MNEMONIC SATOPTS  IN KEYWORD ENDSCALE                      
</warning>
<warning date="1/1/2007" time="0.00000000000000">
 UNRECOGNISED MNEMONIC HYSTER   IN KEYWORD ENDSCALE                      
</warning>
<message date="1/1/2007" time="0.00000000000000">
 NOMIX    IS NOT AVAILABLE IN ECLIPSE 100                                
 AND HAS BEEN IGNORED                                                    
</message>
<warning date="1/1/2007" time="0.00000000000000">
 AIM      METHOD IS NOT AVAILABLE IN ECLIPSE 100                         
 CHOICES ARE FULLY IMPLICIT (DEFAULT) OR IMPES                           
</warning>
<message date="1/1/2007" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<error date="1/1/2007" time="0.00000000000000">
 LICENSE FAILURE: ERROR NUMBER IS -1                                     
</error>
</eclipse>
