<eclipse>
<message date="20/10/1982" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="20/10/1982" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
     279160 BYTES                                                        
</message>
<message date="20/10/1982" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="20/10/1982" time="0.00000000000000">
 NEITHER OLDTRAN,OLDTRANR NOR NEWTRAN SPECIFIED                          
 BLOCK CENTRE TRANSMISSIBILITIES TO BE CALCULATED                        
 USING  OLDTRAN                                                          
</message>
<comment date="20/10/1982" time="0.00000000000000">
 NO NON-NEIGHBOUR CONNECTIONS IN GLOBAL GRID                             
</comment>
<message date="20/10/1982" time="0.00000000000000">
 LGR WORKSPACE USED:                                                     
     6701 INTEGERS,     2021 REALS   (TOTAL    42972 BYTES)              
 LGR WORKSPACE ALLOCATED:                                                
     6711 INTEGERS,     2022 REALS   (TOTAL    43020 BYTES)              
 MINIMUM POSSIBLE RUNSPEC VALUES IN LGR FOR THIS RUN ARE:                
 MAXLGR  =    1     MAXCLS  =    250                                     
 NOTE: NO. OF CELLS IN ANY LOCAL GRID CANNOT EXCEED MAXCLS               
</message>
<message date="20/10/1982" time="0.00000000000000">
 NUMBER OF ACTIVE GLOBAL CELLS IS 300                                    
 NUMBER OF ACTIVE  LOCAL CELLS IS 250                                    
  TOTAL NUMBER OF ACTIVE CELLS IS 550                                    
</message>
<message date="20/10/1982" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SOLUTION SECTION IS                  
       1720 KBYTES                                                       
</message>
<message date="20/10/1982" time="0.00000000000000">
    58620 CHARACTER VARIABLES USED                                       
</message>
<warning date="20/10/1982" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   8704.35517 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.03003                              
</warning>
<warning date="20/10/1982" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   9014.70000 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.06816                              
</warning>
<message date="20/10/1982" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SCHEDULE SECTION IS                  
       1641 KBYTES                                                       
</message>
<message date="11/11/1982" time="22.50000000000000">
 **********************************************************              
 * THE WORST-OFFENDING CONNECTION - BLOCK (  3,  3, 10)   *              
 * IN WELL PROD1    AND ALL BELOW IT ARE CLOSED           *              
 * AT TIME      30.00   DAYS  , BECAUSE                   *              
 * THE WELL     WATER CUT      1.5391E-01                 *              
 * EXCEEDS THE LIMIT   1.5000E-01         .               *              
 **********************************************************              
</message>
<message date="19/11/1982" time="15.00000000000000">
 ******************************************                              
 * WELL PROD2    HAS CHANGED TO           *                              
 * CONTROL BY WATER RATE                  *                              
 * FROM TIME     15.00   DAYS  .          *                              
 ******************************************                              
</message>
<warning date="19/11/1982" time="30.00000000000000">
 GUIDE RATE PHASE OF WELL IG1      SET IN WGRUPCON                       
 IS BEING CHANGED TO 'RAT' AS IT IS AN INJECTOR.                         
</warning>
<warning date="19/11/1982" time="30.00000000000000">
 GUIDE RATE PHASE OF WELL IG2      SET IN WGRUPCON                       
 IS BEING CHANGED TO 'RAT' AS IT IS AN INJECTOR.                         
</warning>
<message date="19/12/1982" time="45.00000000000000">
 ******************************************                              
 * WELL IW1      HAS CHANGED TO           *                              
 * CONTROL BY BOTTOM HOLE PRESSURE        *                              
 * FROM TIME     45.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="19/12/1982" time="60.00000000000000">
 ******************************************                              
 * WELL PROD1    HAS CHANGED TO           *                              
 * CONTROL BY RESERVOIR FLUID VOLUME RATE *                              
 * FROM TIME     60.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="19/12/1982" time="60.00000000000000">
 **********************************************************              
 * THE WORST-OFFENDING CONNECTION - BLOCK (  3,  3,  9)   *              
 * IN WELL PROD1    AND ALL BELOW IT ARE CLOSED           *              
 * AT TIME      75.00   DAYS  , BECAUSE                   *              
 * THE WELL     WATER CUT      1.5391E-01                 *              
 * EXCEEDS THE LIMIT   1.5000E-01         .               *              
 **********************************************************              
</message>
<message date="3/1/1983" time="60.00000000000000">
 ******************************************                              
 * WELL IW2      HAS CHANGED TO           *                              
 * CONTROL BY BOTTOM HOLE PRESSURE        *                              
 * FROM TIME     60.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="27/1/1983" time="75.00000000000000">
 ******************************************                              
 * WELL PROD2    HAS CHANGED TO           *                              
 * CONTROL BY OIL RATE                    *                              
 * FROM TIME     75.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="15/9/1983" time="278.94143364112733">
 ******************************************                              
 * WELL PROD2    HAS CHANGED TO           *                              
 * CONTROL BY WATER RATE                  *                              
 * FROM TIME    278.94   DAYS  .          *                              
 ******************************************                              
</message>
<message date="15/9/1983" time="278.94143364112733">
 ******************************************                              
 * WELL PROD3    HAS CHANGED TO           *                              
 * CONTROL BY GAS RATE                    *                              
 * FROM TIME    278.94   DAYS  .          *                              
 ******************************************                              
</message>
<message date="15/9/1983" time="278.94143364112733">
 ******************************************                              
 * WELL PROD4    HAS CHANGED TO           *                              
 * CONTROL BY LIQUID RATE                 *                              
 * FROM TIME    278.94   DAYS  .          *                              
 ******************************************                              
</message>
<message date="15/9/1983" time="278.94143364112733">
 ******************************************                              
 * WELL PROD5    HAS CHANGED TO           *                              
 * CONTROL BY BOTTOM HOLE PRESSURE        *                              
 * FROM TIME    278.94   DAYS  .          *                              
 ******************************************                              
</message>
<message date="15/9/1983" time="278.94143364112733">
 **********************************************************              
 * THE WORST-OFFENDING CONNECTION - BLOCK (  3,  3,  3)   *              
 * IN WELL PROD2    AND ALL BELOW IT ARE CLOSED           *              
 * AT TIME     330.00   DAYS  , BECAUSE                   *              
 * THE WELL     WATER CUT      2.4835E-01                 *              
 * EXCEEDS THE LIMIT   2.4000E-01         .               *              
 **********************************************************              
</message>
<message date="4/11/1983" time="330.00000000000000">
 ******************************************                              
 * WELL PROD2    HAS CHANGED TO           *                              
 * CONTROL BY OIL RATE                    *                              
 * FROM TIME    330.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="4/11/1983" time="330.00000000000000">
 **********************************************************              
 * THE WORST-OFFENDING CONNECTION - BLOCK (  3,  3,  2)   *              
 * IN WELL PROD2    AND ALL BELOW IT ARE CLOSED           *              
 * AT TIME     380.00   DAYS  , BECAUSE                   *              
 * THE WELL   GAS-OIL RATIO    2.0083E+00 MSCF/STB        *              
 * EXCEEDS THE LIMIT   2.0000E+00 MSCF/STB.               *              
 **********************************************************              
</message>
<message date="4/11/1983" time="330.00000000000000">
 ****************************************************************        
 * WELL PROD2    IS  SHUT   AT TIME     380.00   DAYS   BECAUSE *        
 * IT HAS NO CONNECTIONS OPEN TO THE RESERVOIR.                 *        
 ****************************************************************        
</message>
<message date="28/1/1984" time="430.00000000000000">
 ****************************************************************        
 * WELL PROD3    IS STOPPED AT TIME     465.00   DAYS   BECAUSE *        
 * THE WELL  WATER-GAS RATIO   1.2899E-01 STB/MSCF              *        
 * EXCEEDS THE LIMIT   1.1000E-01 STB/MSCF.                     *        
 ****************************************************************        
</message>
<message date="3/3/1984" time="465.00000000000000">
 **********************************************************              
 * THE WORST-OFFENDING CONNECTION - BLOCK (  7,  7,  2)   *              
 * IN WELL PROD5    IS CLOSED                             *              
 * AT TIME     500.00   DAYS  , BECAUSE                   *              
 * THE WELL     WATER CUT      3.3940E-01                 *              
 * EXCEEDS THE LIMIT   3.0000E-01         .               *              
 **********************************************************              
</message>
<message date="26/4/1984" time="500.00000000000000">
 ******************************************                              
 * WELL IW1      HAS CHANGED TO           *                              
 * CONTROL BY WATER RATE                  *                              
 * FROM TIME    500.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="26/4/1984" time="500.00000000000000">
 ******************************************                              
 * WELL IW2      HAS CHANGED TO           *                              
 * CONTROL BY WATER RATE                  *                              
 * FROM TIME    500.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="13/6/1984" time="554.47606030009251">
 **********************************************************              
 * THE WORST-OFFENDING CONNECTION - BLOCK (  7,  7,  1)   *              
 * IN WELL PROD5    IS CLOSED                             *              
 * AT TIME     602.24   DAYS  , BECAUSE                   *              
 * THE WELL     WATER CUT      4.3092E-01                 *              
 * EXCEEDS THE LIMIT   3.0000E-01         .               *              
 **********************************************************              
</message>
<message date="13/6/1984" time="554.47606030009251">
 ****************************************************************        
 * WELL PROD5    IS  SHUT   AT TIME     602.24   DAYS   BECAUSE *        
 * IT HAS NO CONNECTIONS OPEN TO THE RESERVOIR.                 *        
 ****************************************************************        
</message>
</eclipse>
