<eclipse>
<message date="1/1/1994" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/1994" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
     525028 BYTES                                                        
</message>
<warning date="1/1/1994" time="0.00000000000000">
    800 VALUES NOT DEFINED IN BOX (  1- 20,  1- 20,  1-  3)              
 OF KEYWORD TOPS                                                         
</warning>
<message date="1/1/1994" time="0.00000000000000">
 UNSPECIFIED TOPS VALUES OBTAINED BY ADDING DZ                           
 TO TOPS VALUE FOR LAYER ABOVE                                           
</message>
<message date="1/1/1994" time="0.00000000000000">
 NEITHER OLDTRAN,OLDTRANR NOR NEWTRAN SPECIFIED                          
 BLOCK CENTRE TRANSMISSIBILITIES TO BE CALCULATED                        
 USING  OLDTRAN                                                          
</message>
<message date="1/1/1994" time="0.00000000000000">
 NUMBER OF ACTIVE CELLS IS 1200                                          
</message>
<message date="1/1/1994" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SOLUTION SECTION IS                  
       2039 KBYTES                                                       
</message>
<message date="1/1/1994" time="0.00000000000000">
    58535 CHARACTER VARIABLES USED                                       
</message>
<warning date="1/1/1994" time="0.00000000000000">
 INCONSISTENT END POINTS IN SATURATION TABLE   1                         
 THE MAXIMUM GAS SATURATION (1.0000)                                     
 PLUS THE CONNATE WATER SATURATION (0.1200)                              
 MUST NOT EXCEED 1.0                                                     
</warning>
<warning date="1/1/1994" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   6531.94138 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.01230                              
</warning>
<warning date="1/1/1994" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   6842.28621 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.07111                              
</warning>
<warning date="1/1/1994" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   7152.63103 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.12539                              
</warning>
<warning date="1/1/1994" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   7462.97586 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.17567                              
</warning>
<warning date="1/1/1994" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   7773.32069 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.22244                              
</warning>
<warning date="1/1/1994" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   8083.66552 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.26608                              
</warning>
<warning date="1/1/1994" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   8394.01034 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.30695                              
</warning>
<warning date="1/1/1994" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   8704.35517 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.34534                              
</warning>
<warning date="1/1/1994" time="0.00000000000000">
  NEGATIVE COMPRESSIBILITY FOUND IN GAS                                  
  PRESSURE TABLE     1 AND OIL PRESSURE                                  
  TABLE     1 AT A SAMPLE PRESSURE VALUE                                 
   9014.70000 . ADJUST SATURATED FLUID                                   
  PROPERTY VALUES AT THIS PRESSURE.                                      
  NEGATIVE COMPRESSIBILITIES OCCUR                                       
  FOR GAS SATURATIONS LESS THAN     0.38150                              
</warning>
<message date="1/1/1994" time="0.00000000000000">
 DRSDT KEYWORD HAS NOT BEEN ENTERED, SO THE                              
 MAXIMUM GAS RE-SOLUTION RATE IS DEFAULTED TO INFINITY.                  
</message>
<message date="2/1/1994" time="1.00000000000000">
 RESTART FILE WRITTEN   REPORT     1                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<message date="12/1/1994" time="11.00000000000000">
 RESTART FILE WRITTEN   REPORT     2                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<problem date="22/1/1994" time="21.54928395637633">
 NON-LINEAR EQUATION CONVERGENCE FAILURE                                 
 ITERATION LIMIT REACHED - TIME STEP CHOPPED FROM   4.95                 
</problem>
<warning date="6/3/1994" time="64.36561858846807">
 LINEAR EQUATIONS NOT FULLY CONVERGED - RUN MAY GO FASTER                
 IF YOU INCREASE LITMAX (= 25 - TUNING KEYWORD)                          
</warning>
<warning date="6/3/1994" time="64.36561858846807">
 LINEAR EQUATIONS NOT FULLY CONVERGED - RUN MAY GO FASTER                
 IF YOU INCREASE LITMAX (= 25 - TUNING KEYWORD)                          
</warning>
<warning date="6/3/1994" time="64.36561858846807">
 LINEAR CONVERGENCE FAILURE ON LAST NUPCOL ITERATION.                    
 GROUP TARGETS AND LIMITS MAY NOT BE ACCURATELY HONORED.                 
 YOU MAY NEED TO INCREASE THE CURRENT VALUE OF    4                      
 USING THE NUPCOL KEYWORD.                                               
</warning>
<warning date="5/4/1994" time="94.69701783508614">
 LINEAR EQUATIONS NOT FULLY CONVERGED - RUN MAY GO FASTER                
 IF YOU INCREASE LITMAX (= 25 - TUNING KEYWORD)                          
</warning>
<message date="22/4/1994" time="111.00000000000000">
 RESTART FILE WRITTEN   REPORT     3                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
<warning date="22/4/1994" time="111.00000000000000">
 LINEAR EQUATIONS NOT FULLY CONVERGED - RUN MAY GO FASTER                
 IF YOU INCREASE LITMAX (= 25 - TUNING KEYWORD)                          
</warning>
<warning date="14/5/1994" time="133.57128908399318">
 LINEAR EQUATIONS NOT FULLY CONVERGED - RUN MAY GO FASTER                
 IF YOU INCREASE LITMAX (= 25 - TUNING KEYWORD)                          
</warning>
<warning date="14/5/1994" time="133.57128908399318">
 LINEAR EQUATIONS NOT FULLY CONVERGED - RUN MAY GO FASTER                
 IF YOU INCREASE LITMAX (= 25 - TUNING KEYWORD)                          
</warning>
<warning date="14/5/1994" time="133.57128908399318">
 LINEAR EQUATIONS NOT FULLY CONVERGED - RUN MAY GO FASTER                
 IF YOU INCREASE LITMAX (= 25 - TUNING KEYWORD)                          
</warning>
<warning date="14/5/1994" time="133.57128908399318">
 LINEAR CONVERGENCE FAILURE ON LAST NUPCOL ITERATION.                    
 GROUP TARGETS AND LIMITS MAY NOT BE ACCURATELY HONORED.                 
 YOU MAY NEED TO INCREASE THE CURRENT VALUE OF    4                      
 USING THE NUPCOL KEYWORD.                                               
</warning>
<warning date="14/5/1994" time="133.57128908399318">
 LINEAR EQUATIONS NOT FULLY CONVERGED - RUN MAY GO FASTER                
 IF YOU INCREASE LITMAX (= 25 - TUNING KEYWORD)                          
</warning>
<warning date="14/6/1994" time="164.45264003475722">
 LINEAR EQUATIONS NOT FULLY CONVERGED - RUN MAY GO FASTER                
 IF YOU INCREASE LITMAX (= 25 - TUNING KEYWORD)                          
</warning>
<message date="16/1/1997" time="1111.00000000000000">
 RESTART FILE WRITTEN   REPORT     4                                     
 RESTART INCLUDES WATER AND GAS PHASE PRESSURES                          
</message>
</eclipse>
