<eclipse>
<error date="1/1/0" time="0.00000000000000">
 UNRECOGNISED KEYWORD THERMAL  IN RUNSPEC DATA                           
</error>
<error date="1/1/0" time="0.00000000000000">
 UNRECOGNISED KEYWORD COMPS    IN RUNSPEC DATA                           
</error>
<warning date="1/1/0" time="0.00000000000000">
 SPURIOUS DATA BEFORE WATER    KEYWORD                                   
 2 /             2 hydrocarbon components, volatile oil & gas            
</warning>
<message date="1/1/0" time="0.00000000000000">
  HWELLS IS NOT REQUIRED IN ECLIPSE 100                                  
</message>
<error date="1/1/0" time="0.00000000000000">
 UNRECOGNISED KEYWORD ROCKDIMS IN RUNSPEC DATA                           
</error>
<warning date="1/1/0" time="0.00000000000000">
 SPURIOUS DATA BEFORE WELLDIMS KEYWORD                                   
 2   /           Base and cap rock connections                           
</warning>
<message date="1/1/0" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/1996" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/1996" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
       3410 KBYTES                                                       
</message>
<warning date="1/1/1996" time="0.00000000000000">
   8400 VALUES NOT DEFINED IN BOX (  1- 30,  1- 20,  1- 15)              
 OF KEYWORD TOPS                                                         
</warning>
<error date="1/1/1996" time="0.00000000000000">
 UNRECOGNISED KEYWORD DZV      IN GRID DATA                              
</error>
<warning date="1/1/1996" time="0.00000000000000">
 SPURIOUS DATA BEFORE EQUALS   KEYWORD                                   
  15*2.0  /                              z-height = 30 meters            
</warning>
<error date="1/1/1996" time="0.00000000000000">
 INVALID GRID ARRAY NAME HEATCR                                          
 ON RECORD   45 FOLLOWING EQUALS   KEYWORD                               
</error>
<error date="1/1/1996" time="0.00000000000000">
 GRID ARRAY THCONR   NOT ALLOWED WITH CURRENT                            
 RUNSPEC OPTIONS. SEE KEYWORD TEMP                                       
</error>
<error date="1/1/1996" time="0.00000000000000">
 UNRECOGNISED KEYWORD ROCKCON  IN GRID DATA                              
</error>
<warning date="1/1/1996" time="0.00000000000000">
 SPURIOUS DATA BEFORE ROCKPROP KEYWORD                                   
   1  1 30  1 20  1  1 K- /                   overburden  connect        
   2  1 30  1 20 15 15 K+ /                   underburden connect        
 /                                                                       
</warning>
<error date="1/1/1996" time="0.00000000000000">
 UNRECOGNISED KEYWORD ROCKPROP IN GRID DATA                              
</error>
<warning date="1/1/1996" time="0.00000000000000">
 SPURIOUS DATA BEFORE RPTGRID  KEYWORD                                   
   1 16.0     74.9              1169.0  /     overburden  propert        
   2 16.0     74.9              1169.0  /     underburden propert        
 /                                                                       
</warning>
<message date="1/1/1996" time="0.00000000000000">
 UNSPECIFIED TOPS VALUES OBTAINED BY ADDING DZ                           
 TO TOPS VALUE FOR LAYER ABOVE                                           
</message>
<message date="1/1/1996" time="0.00000000000000">
 NEITHER OLDTRAN,OLDTRANR NOR NEWTRAN SPECIFIED                          
 BLOCK CENTRE TRANSMISSIBILITIES TO BE CALCULATED                        
 USING  OLDTRAN                                                          
</message>
<error date="1/1/1996" time="0.00000000000000">
 INSUFFICIENT DATA TO COMPUTE PORE VOLUMES                               
 PORE VOLUMES WILL BE SET TO ZERO                                        
</error>
<error date="1/1/1996" time="0.00000000000000">
 INSUFFICIENT DATA TO COMPUTE CELL CENTRE DEPTHS                         
 Stop limit reached on error      outputs
</error>
<error date="1/1/1996" time="0.00000000000000">
 INSUFFICIENT DATA TO COMPUTE X TRANSMISSIBILITIES                       
</error>
<error date="1/1/1996" time="0.00000000000000">
 RUN STOPPED BECAUSE NUMBER OF   ERRORS                                  
 EXCEEDS MAXIMUM PERMITTED VALUE (    10).                               
 SEE MESSAGES KEYWORD                                                    
</error>
</eclipse>
