<eclipse>
<error date="1/1/0" time="0.00000000000000">
 UNRECOGNISED KEYWORD THERMAL  IN RUNSPEC DATA                           
</error>
<error date="1/1/0" time="0.00000000000000">
 UNRECOGNISED KEYWORD COMPS    IN RUNSPEC DATA                           
</error>
<warning date="1/1/0" time="0.00000000000000">
 SPURIOUS DATA BEFORE WATER    KEYWORD                                   
 2 /             2 hydrocarbon components, dead oil + solution ga        
</warning>
<message date="1/1/0" time="0.00000000000000">
  HWELLS IS NOT REQUIRED IN ECLIPSE 100                                  
</message>
<error date="1/1/0" time="0.00000000000000">
 UNRECOGNISED KEYWORD ROCKDIMS IN RUNSPEC DATA                           
</error>
<warning date="1/1/0" time="0.00000000000000">
 SPURIOUS DATA BEFORE WELLDIMS KEYWORD                                   
 2  /            Base and cap rock connections                           
</warning>
<message date="1/1/0" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<error date="1/1/0" time="0.00000000000000">
 LICENSE ERROR  -1 FOR MULTI-SEGMENT WELL OPTION                         
 FEATURE IS INVALID. CHECK YOUR LICENSE FILE AND                         
 THE LICENSE LOG FILE                                                    
</error>
</eclipse>
