<eclipse>
<error date="1/1/0" time="0.00000000000000">
 UNRECOGNISED KEYWORD COMPS    IN RUNSPEC DATA                           
</error>
<warning date="1/1/0" time="0.00000000000000">
 SPURIOUS DATA BEFORE THERMAL  KEYWORD                                   
 4 /                                                                     
</warning>
<error date="1/1/0" time="0.00000000000000">
 UNRECOGNISED KEYWORD THERMAL  IN RUNSPEC DATA                           
</error>
<error date="1/1/0" time="0.00000000000000">
 UNRECOGNISED KEYWORD HEATDIMS IN RUNSPEC DATA                           
</error>
<warning date="1/1/0" time="0.00000000000000">
 SPURIOUS DATA BEFORE ROCKDIMS KEYWORD                                   
 5 /                                                                     
</warning>
<error date="1/1/0" time="0.00000000000000">
 UNRECOGNISED KEYWORD ROCKDIMS IN RUNSPEC DATA                           
</error>
<warning date="1/1/0" time="0.00000000000000">
 SPURIOUS DATA BEFORE START    KEYWORD                                   
 2 /                                                                     
</warning>
<warning date="1/1/2000" time="0.00000000000000">
 THE NUMBER OF WELLS HAS BEEN DEFAULTED TO ZERO                          
 USING KEYWORD WELLDIMS IN THE RUNSPEC SECTION                           
 OR NO WELLS WERE FOUND IN THE SCHEDULE SECTION                          
</warning>
<error date="1/1/2000" time="0.00000000000000">
 INPUT RESTART FILE                                                      
 THERM12.X0012                                                           
 DOES NOT EXIST                                                          
</error>
<error date="1/1/2000" time="0.00000000000000">
  I/O ERROR UNABLE TO OPEN RESTART FILE                                  
  ERROR CODE IS :            1                                           
</error>
<message date="1/1/2000" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<error date="1/1/2000" time="0.00000000000000">
 LICENSE FAILURE: ERROR NUMBER IS -1                                     
</error>
</eclipse>
